config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'inicio#inicio'

  get 'naves' => 'naves#naves'
  get 'personas' => 'personajes#personas'
  get 'planetas' => 'planetas#planetas'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController

  def inicio
    x = HTTParty.get("https://swapi.co/api/films/")

    @x = JSON.parse(x.body)["results"]
    peliculas = []
    @x.each do |p|
      aux = []
      aux.push(p["title"])
      aux.push(p["release_date"])
      aux.push(p["episode_id"])
      aux.push(p["director"])
      aux.push(p["producer"])
      peliculas.push(aux)
    end
    @nombres = peliculas


  end
end

app/controllers/naves_controller.rb
class NavesController < ApplicationController
    def naves
      x = HTTParty.get("https://swapi.co/api/starships/")

      @x2 = JSON.parse(x.body)
      @x = @x2['results']
      while true
        if @x2['next'].nil?
          break
        else
          aux = JSON.parse(HTTParty.get(@x2['next']).body)
          @x2 = aux
          aux['results'].each do |p|
            @x.push(p)
          end
        end
        end

      naves = []
      @x.each do |p|
        aux = []
        aux.push(p["name"])
        aux.push(p["url"])
        naves.push(aux)
      end
      @nombres = naves


    end
  end

app/controllers/peliculas_controller.rb
class PeliculasController < ApplicationController




end

app/controllers/personajes_controller.rb
class PersonajesController < ApplicationController
  def personas
    x = HTTParty.get("https://swapi.co/api/people/")
    @x2 = JSON.parse(x.body)
    @x = @x2['results']
    while true
      if @x2['next'].nil?
        break
      else
        aux = JSON.parse(HTTParty.get(@x2['next']).body)
        @x2 = aux
        aux['results'].each do |p|
          @x.push(p)
        end
      end
      end

    personas = []
    @x.each do |p|
      aux = []
      aux.push(p["name"])
      aux.push(p["url"])
      personas.push(aux)
    end
    @nombres = personas


  end
end

app/controllers/planetas_controller.rb
class PlanetasController < ApplicationController
    def planetas
    x = HTTParty.get("https://swapi.co/api/planets/")
    @x2 = JSON.parse(x.body)
    @x = @x2['results']
    while true
      if @x2['next'].nil?
        break
      else
        aux = JSON.parse(HTTParty.get(@x2['next']).body)
        @x2 = aux
        aux['results'].each do |p|
          @x.push(p)
        end
      end
      end

    personas = []
    @x.each do |p|
      aux = []
      aux.push(p["name"])
      aux.push(p["url"])
      personas.push(aux)
    end
    @nombres = personas


  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/naves_helper.rb
module NavesHelper
end

app/helpers/peliculas_helper.rb
module PeliculasHelper
end

app/helpers/personajes_helper.rb
module PersonajesHelper
end

app/helpers/planetas_helper.rb
module PlanetasHelper
end

app/views/inicio/inicio.html.erb
<h1></h1>
<body>
  <table>
      <thead>
          <tr>
            <th>Nombre</th>
            <th>Año de lanzamiento</th>
            <th>Episodio</th>
            <th>Director</th>
            <th>Productores</th>
          </tr>
      </thead>
      <tbody>
        <%@nombres.each do |peli|%>
          <tr>
            <%peli.each do |c|%>
                <td><%=c%></td>
                <% end %>
          </tr>
          <% end %>
      </tbody>
  </table>
</body>

app/views/layouts/application.html.erb
!DOCTYPE html>
<html>
  <head>
    <title>SWinfo</title>
    <%= csrf_meta_tags %>
    <!-- Custom styles for this template -->
      <link href="https://blackrockdigital.github.io/startbootstrap-4-col-portfolio/css/4-col-portfolio.css" rel="stylesheet">
      <link href="https://blackrockdigital.github.io/startbootstrap-4-col-portfolio/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <header class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="navbar-class">
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <p class="navbar-text pull-left">
            <%=link_to "INICIO", root_path, :class => 'navbar-link' %>
            <%=link_to "PERSONAS", personas_path, :class => 'navbar-link' %>
            <%=link_to "NAVES", naves_path, :class => 'navbar-link' %>
            <%=link_to "PLANETAS", planetas_path, :class => 'navbar-link' %>
         </p>
          <p class="navbar-text pull-right">

         </p>
        </div>
      </div>
    </header>
       <% if notice %><p class="alert alert-info"><%= notice %></p><%end%>
       <% if alert %><p class="alert alert-warning"><%= alert %></p><%end%>

      <%= yield %>
  </head>
    <body>
      </body>
    </html>

app/views/naves/naves.html.erb
<h1>Naves</h1>
<body>
  <table>
      <thead>
          <tr>
            <th>Nombre</th>
          </tr>
      </thead>
      <tbody>
        <%@nombres.each do |peli|%>
          <tr>
              <td><%=peli[0]%></td>
          </tr>
          <% end %>
      </tbody>
  </table>
</body>

app/views/personajes/personas.html.erb
<h1>Personas</h1>
<body>
  <table>
      <thead>
          <tr>
            <th>Nombre</th>
          </tr>
      </thead>
      <tbody>
        <%@nombres.each do |peli|%>
          <tr>
              <td><%=peli[0]%></td>
          </tr>
          <% end %>
      </tbody>
  </table>
</body>

app/views/planetas/planetas.html.erb
<h1>Planetas</h1>
<body>
  <table>
      <thead>
          <tr>
            <th>Nombre</th>
          </tr>
      </thead>
      <tbody>
        <%@nombres.each do |peli|%>
          <tr>
              <td><%=peli[0]%></td>
          </tr>
          <% end %>
      </tbody>
  </table>
</body>